// Sample products for demo
import { Product, Category } from '@/types';

export const sampleCategories: Category[] = [
  { id: 1, name: 'Semua', slug: 'all', createdAt: new Date() },
  { id: 2, name: 'Makanan', slug: 'food', createdAt: new Date() },
  { id: 3, name: 'Minuman', slug: 'drinks', createdAt: new Date() },
  { id: 4, name: 'Snack', slug: 'snack', createdAt: new Date() },
  { id: 5, name: 'Rokok', slug: 'cigarette', createdAt: new Date() },
  { id: 6, name: 'Kebutuhan Rumah', slug: 'household', createdAt: new Date() },
];

export const sampleProducts: Product[] = [
  {
    id: '1',
    sku: 'PRD001',
    name: 'Indomie Goreng',
    price: 3500,
    costPrice: 2800,
    stockQuantity: 150,
    lowStockThreshold: 20,
    categoryId: 2,
    barcode: '8992388888888',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    sku: 'PRD002',
    name: 'Aqua 600ml',
    price: 4000,
    costPrice: 3000,
    stockQuantity: 200,
    lowStockThreshold: 30,
    categoryId: 3,
    barcode: '8992388888889',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    sku: 'PRD003',
    name: 'Teh Botol Sosro',
    price: 5000,
    costPrice: 3800,
    stockQuantity: 80,
    lowStockThreshold: 15,
    categoryId: 3,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    sku: 'PRD004',
    name: 'Chitato Sapi Panggang',
    price: 12000,
    costPrice: 9500,
    stockQuantity: 45,
    lowStockThreshold: 10,
    categoryId: 4,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    sku: 'PRD005',
    name: 'Pocari Sweat 500ml',
    price: 8500,
    costPrice: 6800,
    stockQuantity: 60,
    lowStockThreshold: 12,
    categoryId: 3,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '6',
    sku: 'PRD006',
    name: 'Gudang Garam Filter',
    price: 28000,
    costPrice: 25000,
    stockQuantity: 35,
    lowStockThreshold: 10,
    categoryId: 5,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '7',
    sku: 'PRD007',
    name: 'Rinso Cair 800ml',
    price: 22000,
    costPrice: 18000,
    stockQuantity: 25,
    lowStockThreshold: 8,
    categoryId: 6,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '8',
    sku: 'PRD008',
    name: 'Oreo Original',
    price: 10000,
    costPrice: 8000,
    stockQuantity: 8,
    lowStockThreshold: 10,
    categoryId: 4,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '9',
    sku: 'PRD009',
    name: 'Kopi Good Day',
    price: 3000,
    costPrice: 2200,
    stockQuantity: 100,
    lowStockThreshold: 20,
    categoryId: 3,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '10',
    sku: 'PRD010',
    name: 'Sampoerna Mild',
    price: 30000,
    costPrice: 27000,
    stockQuantity: 0,
    lowStockThreshold: 10,
    categoryId: 5,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '11',
    sku: 'PRD011',
    name: 'Mie Sedaap Kari',
    price: 3200,
    costPrice: 2600,
    stockQuantity: 120,
    lowStockThreshold: 25,
    categoryId: 2,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '12',
    sku: 'PRD012',
    name: 'Sunlight Jeruk 400ml',
    price: 12500,
    costPrice: 10000,
    stockQuantity: 40,
    lowStockThreshold: 10,
    categoryId: 6,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
